### ISSUE TITLE
AspNetCore: OpenId Cookies always show expires=1969-12-31 even with IsPersistent=true and ExpireTimeSpan set

### ISSUE THREAD

**Issue by sathiathirumal** [aspnet/Security#1752]
Using ASPNETCORE OpenId authentication middleware and Cookie middleware. I always see that cookies from OpenId authentication are set to expire at 1969-12-31 (in Chrome debugger). I assume this means the cookies are SESSION cookies; I want to make them persistent cookies so the user will be prompted to login less frequently. So I added the ExpireTimeSpan and IsPersistent=true as suggested in other posts, but I still see that my cookie Expires is 1969-12-31. 

What am I doing wrong?

[![enter image description here][1]][1]

            services.AddAuthentication(options =>
            {
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddAzureAd(options =>
            {
                Configuration.Bind("AzureAd", options);
            })
            .AddCookie(p =>
            {
                p.ExpireTimeSpan = TimeSpan.FromDays(30);
                p.SlidingExpiration = true;
            });

            services.Configure<AuthenticationProperties>(props =>
            {
                props.IsPersistent = true;
                props.ExpiresUtc = new DateTimeOffset(DateTime.Now, TimeSpan.FromDays(30));
            });

  [1]: https://i.stack.imgur.com/nDHzg.png

**Comment by Tratcher** [comment]
`Configure<AuthenticationProperties>` is not a thing. Where do you call challenge?

**Comment by sathiathirumal** [comment]
@Tratcher - I dont invoke the challenge directly, I am assuming it occurs indirectly via the [Authorize] attribute? re: `Configure<AuthenticationProperties>`, I couldnt find any other way to override the IsPersistent value to true as I dont invoke Sigin(...) directly.

**Comment by sathiathirumal** [comment]
Awesome, thanks @Tratcher . Your first suggestion did the trick. I also implemented a Logout page (call to `AuthenticationHttpContextExtensions.SignOutAsync(HttpContext)`) to give the user more control over cookie lifetimes.

            .AddCookie(p =>
            {
                p.SlidingExpiration = true;
                p.Events.OnSigningIn = (context) =>
                {
                    context.CookieOptions.Expires = DateTimeOffset.UtcNow.AddDays(30);
                    return Task.CompletedTask;
                };
            });

**Comment by syska** [comment]
@sathiathirumal 

Did this work for you? I have an issue where users it being logged out halvway though the session ( Expiration from ADFS is 8 hours ) and then OnSignedIn is being called again ... 

So a little in doubt if "false" here is default ... and I hope setting this to "true" will fix my problem ...

**Comment by sathiathirumal** [comment]
@syska

Yes this does work for me. IsPersistent is false as per Tratcher. I am using the exact block of code as i pasted above, everything else is default values.

**Comment by syska** [comment]
@sathiathirumal 

Deplyoed an update to the site yesterday including lots of logging about to see whats actually going on ... and an Expires of 8 hours ... 

Should be able to see if users still gets logged out after 4 hours ...
